---
title: "BaseballViz"
author: "Eric Drew"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(baseballr)
library(tidyverse)
library(etl)
library(devtools)
library(Lahman)
```

```{r data}
#RAFFY: 646240
raffy <- scrape_statcast_savant(start_date = '2022-05-01',
                                  end_date = '2022-11-30',
                                  playerid = 646240,
                                  player_type = 'batter')
```
```{r}
raffy_bip <- raffy %>%
              filter(type=='X') 

raffy_bip %>% dplyr::select(events, hc_x, hc_y)
```

```{r}
#2022 Spray chart
spray_chart <- function(data, x, y, events){
  ggplot(data= data, aes(x = x, y = -y, color = events)) +
    geom_curve(x = 33, xend=223, y=-100, yend = -100,
               curvature = -.65) +
    geom_segment(x = 128, xend = 33, y = -208, yend = -100) + 
    geom_segment(x = 128, xend = 223, y = -208, yend = -100) + 
    geom_curve(x=83, xend = 173, y = -155, yend = -156,
               curvature = -.65, linetype = 'dotted') + 
    coord_fixed() + 
    scale_x_continuous(NULL, limits = c(25,225)) + 
    scale_y_continuous(NULL, limits = c(-225, -25))
}

spray_chart(raffy_bip, raffy_bip$hc_x, raffy_bip$hc_y, raffy_bip$events) + geom_point()+
  ggtitle("Rafael Devers '22 Season Spraychart") + theme(plot.title = element_text(hjust = 0.5))

```

```{r}
#Expected BA by launch angle/speed
guidelines <- tibble(
  launch_angle = c(10,25,50),
  launch_speed = 40,
  label = c('Ground balls', 'Line drives', 'Flyballs')
)

crcblue <- "#2905a1"

ev_plot <- raffy_bip %>%
  sample_n(nrow(.) / 2) %>%
  ggplot(aes(x = launch_speed, y = launch_angle,
             color = estimated_ba_using_speedangle)) + 
  geom_hline(data= guidelines, aes(yintercept = launch_angle),
             color = 'black', linetype = 2) + 
  geom_text(data= guidelines,
            aes(label = label, y = launch_angle - 4),
            color = 'black', hjust='left') + 
  geom_point(alpha = 0.8) + 
  ggtitle("Devers '22 Season Estimated BA by Launch Angle") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_color_gradient("BA", low = 'red', high = 'blue') +
  scale_x_continuous("Exit Velocity (mph)",
                     limits = c(40,120)) + 
  scale_y_continuous("Launch Angle (degrees)",
                     breaks = seq(-75, 75, 25))
            

ev_plot
```

```{r}
#Career trajectories
people <- Lahman::People
people %>%
  filter(nameFirst=='Rafael', nameLast == 'Devers') %>%
  pull(playerID) -> raffy_id

batting <- Lahman::Batting
batting <- batting %>% replace_na(list(SF = 0, HBP = 0))

get_stats <- function(player.id){
  batting %>%
    filter(playerID == player.id) %>%
    inner_join(people, by = 'playerID') %>%
    mutate(birthyear = ifelse(birthMonth >= 7,
                              birthYear + 1, birthYear),
           Age = yearID - birthYear,
           SLG = (H - X2B - X3B - HR +
                    2 * X2B + 3 * X3B + 4 * HR) / AB,
           OBP = (H + BB + HBP) / (AB + BB + HBP + SF),
           OPS = SLG + OBP) %>%
    select(Age, SLG, OBP, OPS)
}

raffyStats  <- get_stats(raffy_id)

fit_model <- function(d){
  fit <- lm(OPS ~ I(Age-30) + I((Age - 30)^2), data=d)
  b <- coef(fit)
  Age.max <- 30 - b[2] / b[3] /2
  Max <- b[1] - b[2] ^ 2 / b[3] / 4
  list(fit = fit, Age.max = Age.max, Max = Max)
}

F2 <- fit_model(raffyStats)
coef(F2$fit)

ggplot(raffyStats, aes(Age,OPS)) + geom_point() + 
  geom_smooth(method = 'lm', se=FALSE, size = 1.5,
              formula = y ~ poly(x, 2, raw=TRUE)) +
  geom_vline(xintercept = F2$Age.max,
             linetype = 'dashed', color = 'darkgrey') + 
  geom_hline(yintercept = F2$Max,
             linetype = 'dashed', color = 'darkgrey') +
  annotate(geom = 'text', x = c(29,30), y = c(.72, 1.1),
           label = c('Peak Age', "Max"), size = 5)


#Comparing career trajectories

#pull only players who have 2000+ career ABs
batting %>%
  group_by(playerID) %>%
  summarize(Career.AB = sum(AB, na.rm = TRUE)) %>%
  inner_join(batting, by = 'playerID') %>%
  filter(Career.AB >= 2000) -> batting_2000

#add on position info from fielding dataset
fielding <- Lahman::Fielding
fielding %>%
  group_by(playerID, POS) %>%
  summarize(Games = sum(G)) %>%
  arrange(playerID, desc(Games)) %>%
  filter(POS == first(POS)) -> positions

batting_2000 <- batting_2000 %>%
  inner_join(positions, by = 'playerID')

#compute career statistics
vars <- c('G','AB','R','H','X2B','X3B','HR','RBI','BB','SO','SB')

batting %>%
  group_by(playerID) %>%
  summarize_at(vars, sum, na.rm=TRUE) -> C.totals

#calculate career avg and slugging
C.totals %>%
  mutate(AVG = H/AB,
         SLG = (H - X2B - X3B - HR + 2 * X2B + 3 * X3B + 4 * HR) / AB) -> C.totals

#add position values for similarity score calculations
C.totals %>%
  inner_join(positions, by = 'playerID') %>%
  mutate(Value.POS = case_when(POS == 'C' ~ 240,
                               POS == 'SS' ~ 168,
                               POS == '2B' ~ 132,
                               POS == '3B' ~ 84,
                               POS == 'OF' ~ 48,
                               POS == '1B' ~ 12,
                               TRUE ~ 0)) -> C.totals
#Compute similarit scores
similar <- function(p, number = 10){
  C.totals %>% filter(playerID == p) -> P
  C.totals %>%
    mutate(sim_score = 1000 -
             floor(abs(G - P$G) / 20) -
             floor(abs(AB - P$AB) / 75) -
             floor(abs(R - P$R) / 10) -
             floor(abs(H - P$H) / 15) -
             floor(abs(X2B - P$X2B) / 5) -
             floor(abs(X3B - P$X3B) / 4) -
             floor(abs(HR - P$HR) / 2) -
             floor(abs(RBI - P$RBI) / 10) -
             floor(abs(BB - P$BB) / 25) -
             floor(abs(SO - P$SO) / 150) -
             floor(abs(SB - P$SB) / 20) -
             floor(abs(AVG - P$AVG) / .001) -
             floor(abs(SLG - P$SLG) / .002) -
             abs(Value.POS - P$Value.POS)) %>%
    arrange(desc(sim_score)) %>%
    head(number)
}

similar(raffy_id, 6)


#PLOT similar career trajectories

#Define age, OBP, SLG and OPS for every player
batting_2000 %>%
  group_by(playerID, yearID) %>%
  summarize(G = sum(G), AB = sum(AB), R= sum(R), H = sum(H), X2B = sum(X2B), X3B = sum(X3B),
            HR = sum(HR), RBI = sum(RBI), SB = sum(SB), CS = sum(CS), BB = sum(BB),
            SH = sum(SH), SF = sum(SF), HBP = sum(HBP), Career.AB = first(Career.AB),
            POS = first(POS)) %>%
  mutate(SLG = (H - X2B - X3B - HR + 2 * X2B + 3 * X3B + 4 * HR) / AB,
         OBP = (H + BB + HBP) / (AB + BB + HBP + SF),
         OPS = SLG + OBP) -> batting_2000

#get birth year for every player
batting_2000 %>%
  inner_join(people, by = 'playerID') %>%
    mutate(birthyear = ifelse(birthMonth >= 7,
                              birthYear + 1, birthYear),
           Age = yearID - birthyear) -> batting_2000

batting_2000 <- batting_2000 %>% drop_na(Age)


#function to plot similar career trajectories
plot_trajectories <- function(player, n.similar = 5, ncol){
  flnames <- unlist(strsplit(player, " "))
  
  people %>%
    filter(nameFirst == flnames[1],
           nameLast == flnames[2]) %>%
    select(playerID) -> player
  
  player.list <- player %>%
    pull(playerID) %>%
    similar(n.similar) %>%
    pull(playerID)
  
  batting_2000 %>%
    filter(playerID %in% player.list) %>%
    mutate(Name = paste(nameFirst, nameLast)) -> Batting.new
  
  ggplot(Batting.new, aes(Age,OPS)) + 
    geom_smooth(method = 'lm',
                formula = y ~ x + I(x^2),
                size = 1.5) + 
    ggtitle(paste('OPS Trajectories for ', n.similar-1, ' Players Most Similar to ',flnames[1], ' ',str_trim(flnames[2]),"' Career", sep='')) +
    facet_wrap(~ Name, ncol=ncol) + theme_bw() +
    theme(plot.title = element_text(hjust = 0.5))
}

plot_trajectories("Barry Bonds", 6, 2)

```